In [1]:
import numpy as np

In [6]:
# creation numpy array using python list [MATHOD 1]
pylist  = [1,2,3,45,67,99]

arr = np.array(pylist)
print(arr)
# print(arr.shape)

[ 1  2  3 45 67 99]
(6,)


In [7]:
# creating 2d array
arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D)

# print dimension or shape 
print(arr2D.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [11]:
# creating numpy array from scratch with diffrent functions [METHOD 2]

arr_zero = np.zeros((3,3), dtype="int64") #dtype default is float and dimension is (row x cols)
print("\nwith int64 \n",arr_zero)

arr_zero = np.zeros((3,3)) #dimension is (row x cols)
print("\nwith default \n",arr_zero)


with int64 
 [[0 0 0]
 [0 0 0]
 [0 0 0]]

with default 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [14]:
arr_one = np.ones((3,3))
print(arr_one)
print(arr_one.shape)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
(3, 3)


In [22]:
# fill any value

arr_val = np.full((3,3), 99)
print(arr_val)


#  create 1D
arr_val1 = np.full((7,), 100)
print(arr_val1)

[[99 99 99]
 [99 99 99]
 [99 99 99]]
[100 100 100 100 100 100 100]


In [20]:
# create identity matrix
arrIM = np.eye(4 , dtype="int64")
print(arrIM)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [23]:
# fill in range 
arr_rng = np.arange(1,21,2) #(start, end , step)
print(arr_rng)

arr_rng = np.arange(1,21) #(start, end , step)
print(arr_rng)

[ 1  3  5  7  9 11 13 15 17 19]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [25]:
# equally divided ranged array

edarr = np.linspace(1,100,3 , dtype="int64") #(start , end , divided into how much)
print(edarr)

[  1  50 100]
