In [2]:
import numpy as np

In [3]:
# OPERATIONS on NUMPY ARRAY

# 1. RESHAPING

# reshape : convert (2x3) ==> (3x2)
arr = np.array([[1,2,3],[4,5,6]])
print("Normal Array \n",arr , "Dimesnion ==>",arr.shape)


reshape_arr = arr.reshape((3,2))
print("\nReshape Array \n",reshape_arr , "Dimesnion ==>",reshape_arr.shape)


# flatten : convert N-D ===> 1D
flat = arr.flatten()
print("\n1D Array : ",flat)

Normal Array 
 [[1 2 3]
 [4 5 6]] Dimesnion ==> (2, 3)

Reshape Array 
 [[1 2]
 [3 4]
 [5 6]] Dimesnion ==> (3, 2)

1D Array :  [1 2 3 4 5 6]


In [6]:
# 2. Indexing
arr1D = np.array([1,2,3,4,5])
arr2D = np.array([[1,2,3],[4,5,6]])

print(arr1D[0])
print(arr2D[0][2])

1
3


In [9]:
# 3. Fancy Indexing : access multiple indx value at same time

arr = np.array([1,2,3,4,5,7,8,9])

idx = [0,4,5]
print(arr[idx])

[1 5 7]


In [14]:
#  4. Boolean Indexing : based on condn T / F

arr = np.array([1,2,3,4,5,6,7,8,9])

print("Val > 3 :",arr[arr>4])
print("Even :",arr[arr%2 == 0]) 

Val > 3 : [5 6 7 8 9]
Even : [2 4 6 8]


In [17]:
# 4. Slicing (Alert !)
arr = np.array([1,2,3,4,5,6,7,8,9])

print(arr[2:7]) # [start: end : step]
print(arr[::-1])


# Copy vs View 

# Python list slicing -----> COPY OF ARRAY
# Numpy slicing -----> View or original (not copy) , THUS FAST! (Too avoid this use copy() function )

[3 4 5 6 7]
[9 8 7 6 5 4 3 2 1]
