In [2]:
import numpy as np

In [7]:
# Multidimensional axes(axis)
# rows -> 0 axis
# cols -> 1 axis
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)

# total sum
sum = np.sum(arr)
print("Total sum : ", sum)


# cols sum only
colSum = np.sum(arr, axis=0)
print(colSum)


# row sum only
rowSum = np.sum(arr, axis=1)
print(rowSum)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Total sum :  45
[12 15 18]
[ 6 15 24]


In [11]:
# 3D Array
arr3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 12, 13], [14, 51, 16], [17, 18, 19]]])
print(arr3d, arr3d.shape)


# slicing in 3d array
print(arr3d[0, 1, 2])



[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 12 13]
  [14 51 16]
  [17 18 19]]] (2, 3, 3)
6
