In [1]:
import numpy as np

In [3]:
# vectorization

arr = np.array([1, 2, 3, 4, 5])
print(arr + 5)

[ 6  7  8  9 10]


In [6]:
# broadcasting

# Two rules:
# i. (1xM) (NxM) atleast one should present in dimension.
# ii. compare from right to left

arr = np.array([7, 8, 3, 7, 2])
num = np.array([[2, 3, 4, 5, 6] , [6, 5, 8, 2, 3]])

print(arr.shape , num.shape) # (1x5 , 2x5)
print(arr + num)

(5,) (2, 5)
[[ 9 11  7 12  8]
 [13 13 11  9  5]]


In [10]:
# failed case of broadcasting 
# (2x5 , 3x5) ==> no 1 is present.
arr = np.array([ [7, 8, 3, 7, 2] , [7, 8, 3, 7, 2] ])
num = np.array([[2, 3, 4, 5, 6] , [6, 5, 8, 2, 3] , [6, 5, 8, 2, 3]])

print(arr.shape , num.shape) 
# print(arr + num)

(2, 5) (3, 5)


In [13]:
# Normalization : scale value from 0 (mean ) to 1(standard deviation)

num = np.array([[1, 2], [4, 5]])

mean = np.mean(num)
std_dev = np.std(num)

normal = (num - mean)/std_dev
print(normal)

print("mean =" , mean)
print("Std =" , std_dev)

# Normalize Matrix
# [[-1.26491106 -0.63245553]
#  [ 0.63245553  1.26491106]] ===> mean of this matrix is 0 

[[-1.26491106 -0.63245553]
 [ 0.63245553  1.26491106]]
mean = 3.0
Std = 1.5811388300841898
